runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT main:app.server # default is main:app, but this seems to work for this one here
                                            # solution found: https://community.plot.ly/t/deploying-dash-to-google-app-engine/7254/4

runtime_config:
  python_version: 3