import dash_html_components as html
from . import app

about = """
Here is the list of all the screens in our database. 
Please, lt us know if there is any screen missing or if you have an issues with 
any of those screens. Note that some of the screens in our database are not currently working 
but we actively looking into fixing all the issues, so you can use our tool to optimise all the 
commercial screens available. 
"""


about_html = [html.P(i) for i in about.split("\n\n")]


layout = [
 html.Div(
        [
            html.Div(html.H1(app.list_title), id="list_itle"),
            html.H2("About"),
            html.Div(about_html, className="basic_info_container"),

            html.H2("List of screens in our database"),
            html.Div([
                            html.Ol([
                                html.Li(html.P('CryoSol')),
                                html.Li(html.P('MD1-01')),
                                html.Li(html.P('MD1-01-ECO')),
                                html.Li(html.P('MD1-02')),
                                html.Li(html.P('MD1-02-ECO')),
                                html.Li(html.P('MD1-03-ECO')),
                                html.Li(html.P('MD1-04')),
                                html.Li(html.P('MD1-05')),
                                html.Li(html.P('MD1-05-ECO')),
                                html.Li(html.P('MD1-09')),
                                html.Li(html.P('MD1-09-ECO')),
                                html.Li(html.P('MD1-11')),
                                html.Li(html.P('MD1-13')),
                                html.Li(html.P('MD1-13-ECO')),
                                html.Li(html.P('MD1-14')),
                                html.Li(html.P('MD1-15')),
                                html.Li(html.P('MD1-16')),
                                html.Li(html.P('MD1-20')),
                                html.Li(html.P('MD1-20-ECO')),
                                html.Li(html.P('MD1-21')),
                                html.Li(html.P('MD1-22')),
                                html.Li(html.P('MD1-22-ECO')),
                                html.Li(html.P('MD1-24')),
                                html.Li(html.P('MD1-25')),
                                html.Li(html.P('MD1-26')),
                                html.Li(html.P('MD1-27')),
                                html.Li(html.P('MD1-29')),
                                html.Li(html.P('MD1-29-ECO')),
                                html.Li(html.P('MD1-30')),
                                html.Li(html.P('MD1-31')),
                                html.Li(html.P('MD1-31-ECO')),
                                html.Li(html.P('MD1-32')),
                                html.Li(html.P('MD1-32-ECO')),
                                html.Li(html.P('MD1-33')),
                                html.Li(html.P('MD1-34')),
                                html.Li(html.P('MD1-35')),
                                html.Li(html.P('MD1-35-ECO')),
                                html.Li(html.P('MD1-36')),
                                html.Li(html.P('MD1-36-ECO')),
                                html.Li(html.P('MD1-37')),
                                html.Li(html.P('MD1-37-ECO')),
                                html.Li(html.P('MD1-39')),
                                html.Li(html.P('MD1-39-ECO')),
                                html.Li(html.P('MD1-38')),
                                html.Li(html.P('MD1-38-ECO')),
                                html.Li(html.P('MD1-40')),
                                html.Li(html.P('MD1-40-ECO')),
                                html.Li(html.P('MD1-41')),
                                html.Li(html.P('MD1-41-ECO')),
                                html.Li(html.P('MD1-42')),
                                html.Li(html.P('MD1-42-ECO')),
                                html.Li(html.P('MD1-43')),
                                html.Li(html.P('MD1-43-ECO')),
                                html.Li(html.P('MD1-44')),
                                html.Li(html.P('MD1-44-ECO')),
                                html.Li(html.P('MD1-45')),
                                html.Li(html.P('MD1-45-ECO')),
                                html.Li(html.P('MD1-46_47_47-FX')),
                                html.Li(html.P('MD1-47-GREEN')),
                                html.Li(html.P('MD1-48')),
                                html.Li(html.P('MD1-50')),
                                html.Li(html.P('MD1-50-ECO')),
                                html.Li(html.P('MD1-51')),
                                html.Li(html.P('MD1-51-ECO')),
                                html.Li(html.P('MD1-52')),
                                html.Li(html.P('MD1-53')),
                                html.Li(html.P('MD1-55')),
                                html.Li(html.P('MD1-57')),
                                html.Li(html.P('MD1-56')),
                                html.Li(html.P('MD1-63')),
                                html.Li(html.P('MD1-63-ECO')),
                                html.Li(html.P('MD1-63-GREEN')),
                                html.Li(html.P('MD1-64')),
                                html.Li(html.P('MD1-64-GREEN')),
                                html.Li(html.P('MD1-65')),
                                html.Li(html.P('MD1-66')),
                                html.Li(html.P('MD1-67')),
                                html.Li(html.P('MD1-68')),
                                html.Li(html.P('MD1-69')),
                                html.Li(html.P('MD1-70_71')),
                                html.Li(html.P('MD1-74')),
                                html.Li(html.P('MD1-74-ECO')),
                                html.Li(html.P('MD1-74-HT')),
                                html.Li(html.P('MD1-74-HT-ECO')),
                                html.Li(html.P('MD1-86')),
                                html.Li(html.P('MD1-87')),
                                html.Li(html.P('MD1-88')),
                                html.Li(html.P('MD1-88-ECO')),
                                html.Li(html.P('MD1-89')),
                                html.Li(html.P('MD1-89-ECO')),
                                html.Li(html.P('MD1-89-FX')),
                                html.Li(html.P('MD1-91_92_9-FX')),
                                html.Li(html.P('MD1-93')),
                                html.Li(html.P('MD1-95')),
                                html.Li(html.P('MD1-96')),
                                html.Li(html.P('MD1-97')),
                                html.Li(html.P('MD1-98')),
                                html.Li(html.P('MD1-100')),
                                html.Li(html.P('MD1-101')),
                                html.Li(html.P('MD1-102')),
                                html.Li(html.P('MD1-103')),
                                html.Li(html.P('MD1-104')),
                                html.Li(html.P('MD1-104-ECO')),
                                html.Li(html.P('MD1-105')),
                                html.Li(html.P('MD1-105-ECO')),
                                html.Li(html.P('MD1-106')),
                                html.Li(html.P('MD1-107')),
                                html.Li(html.P('MD1-110_111')),
                                html.Li(html.P('MD1-110_111-ECO')),
                                html.Li(html.P('MD1-112_113-ECO')),
                                html.Li(html.P('MD1-112_113')),
                                html.Li(html.P('MD1-114 and MD1-115')),
                                html.Li(html.P('MD1-114-ECO and MD1-115-ECO')),
                                html.Li(html.P('MD1-116_117')),
                                html.Li(html.P('MD1-118')),
                                html.Li(html.P('MD1-121')),
                                html.Li(html.P('MD1-121_122-ECO')),
                                html.Li(html.P('MD1-123')),
                                html.Li(html.P('MD1-125')),
                                html.Li(html.P('Structure Screen')),

                                                            ])], className="notes")], id="main_container",
                                                    **{'data-iframe-height': ''}, style={ 'width': '60%',
                                            'padding': '20px',
                                            'margin': '20px',
                                            'justify-content': 'center','align-items': 'center',
                                        # 'width': '60%', 
                                        # 'margin': 'auto', 'padding': '10px'
                                        }
                                    )
                                ]

